version: 2.1
orbs:
  aws-cli: circleci/aws-cli
  node: circleci/node@1.1

jobs:
  integration-test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: aws sts assume-role --role-arn $DEPLOYER_ARN --role-session-name ci-deploy
            - run: npm ci
            - run: npm run test # run our integration tests
  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: aws sts assume-role --role-arn $DEPLOYER_ARN --role-session-name ci-deploy
            - run: npm run sls -- deploy
  acceptance-test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: aws sts assume-role --role-arn $DEPLOYER_ARN --role-session-name ci-deploy
            - run: npm run acceptance

workflows:
   version: 2
   dev:
     jobs:
       - integration-test
       - deploy:
          requires:
            - integration-test
       - acceptance-test:
          requires:
            - deploy